function html_content = generateHtmlContent(dir, ixmap, hd, len_diff, total_distance)
% This function is for generating a string to save into the html file to
% visualize results

% sorting
[total_sorted, sorted_index] = sort(total_distance);

% css part
html_content = ['<style type=','"text/css','"','>', ...
    '.tg  {border-collapse:collapse;border-spacing:0;}', ...
    '.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}',...
    '.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}',...
    '</style>'];

% table
html_content = [html_content, '<table class="tg">'];
html_content = [html_content, '<tr>', ...
    '<th class="tg-031e">', 'row', '</th>', ...
    '<th class="tg-031e">', 'filename', '</th>', ...
    '<th class="tg-031e">', 'image', '</th>', ...
    '<th class="tg-031e">', 'curv_diff_1', '</th>', ...
    '<th class="tg-031e">', 'curv_diff_2', '</th>', ...
    '<th class="tg-031e">', 'curv_diff_3', '</th>', ...
    '<th class="tg-031e">', 'curv_diff_4', '</th>', ...
    '<th class="tg-031e">', 'len_diff_1', '</th>', ...
    '<th class="tg-031e">', 'len_diff_2', '</th>', ...
    '<th class="tg-031e">', 'len_diff_3', '</th>', ...
    '<th class="tg-031e">', 'len_diff_4', '</th>', ...
    '<th class="tg-031e">', 'total', '</th>', '</tr>'];

for i = 1:length(sorted_index)
    
    index = sorted_index(i);
    
    html_content = [html_content, '<tr> ', ...
        '<th class="tg-031e">', num2str(i), '</th> ', ...
        '<th class="tg-031e">', ixmap{index}, '</th> '];
    
    html_content = [html_content, ...
        '<th class="tg-031e">', '<img src="', ...
        strcat(dir, ixmap{index}, '.png'), '" style="width:150px;height:150px"></th> '];
    
    html_content = [html_content, ...
        '<th class="tg-031e">', num2str(hd(index,1)), '</th> '];
    html_content = [html_content, ...
        '<th class="tg-031e">', num2str(hd(index,2)), '</th> '];
    html_content = [html_content, ...
        '<th class="tg-031e">', num2str(hd(index,3)), '</th> '];
    html_content = [html_content, ...
        '<th class="tg-031e">', num2str(hd(index,4)), '</th> '];
    
    html_content = [html_content, ...
        '<th class="tg-031e">', num2str(len_diff(index,1)), '</th> '];
    html_content = [html_content, ...
        '<th class="tg-031e">', num2str(len_diff(index,2)), '</th> '];
    html_content = [html_content, ...
        '<th class="tg-031e">', num2str(len_diff(index,3)), '</th> '];
    html_content = [html_content, ...
        '<th class="tg-031e">', num2str(len_diff(index,4)), '</th> '];
    
    html_content = [html_content, ...
        '<th class="tg-031e">', num2str(total_distance(index)), '</th> </tr> '];
end

html_content = [html_content, '</table> '];

end


